local base = vgui.Create("DFrame")
base:SetSize(500, 450)
base:SetTitle("CP Rank Officer")
base:Center()
base:SetVisible(true)
base:ShowCloseButton(true)
base:MakePopup()

local divisionSelection = vgui.Create("DComboBox", base)
divisionSelection.SetSize()
divisionSelection:SetPos( 15, 30 )
divisionSelection:SetValue("Select Division")
divisionSelection:AddChoice("UNION")
divisionSelection:AddChoice("GRID")
divisionSelection:AddChoice("JURY")
divisionSelection:AddSpacer()
divisionSelection:AddChoice("KING")
divisionSelection:AddChoice("VICE")